services:
  app:
    build: ./projMagicLook
    container_name: magiclook-app
    ports:
      - "8080:8080"
    networks:
      - monitoring
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/magiclook
      - SPRING_DATASOURCE_USERNAME=magicuser
      - SPRING_DATASOURCE_PASSWORD=magicpass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - APP_ADMIN_PASSWORD=${APP_ADMIN_PASSWORD}
  db:
    image: postgres:15-alpine
    container_name: magiclook-db
    environment:
      - POSTGRES_DB=magiclook
      - POSTGRES_USER=magicuser
      - POSTGRES_PASSWORD=magicpass
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - monitoring
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./config/rules:/etc/prometheus/pyrra"
    ports:
      - 9090:9090
    networks:
      - monitoring
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1s
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitoring

  pyrra-api:
    image: ghcr.io/pyrra-dev/pyrra:v0.7.0
    container_name: pyrra-api
    restart: always
    command:
      - api
      - --prometheus-url=http://prometheus:9090
      - --prometheus-external-url=http://localhost:9090
      - --api-url=http://pyrra-filesystem:9444
    ports:
      - "9099:9099"
    networks:
      - monitoring

  pyrra-filesystem:
    image: ghcr.io/pyrra-dev/pyrra:v0.7.0
    container_name: pyrra-filesystem
    restart: always
    user: root
    command:
      - filesystem
      - --prometheus-url=http://prometheus:9090
      - --generic-rules=true
    volumes:
      - ./config/slos:/etc/pyrra
      - ./config/rules:/etc/prometheus/pyrra
    networks:
      - monitoring

volumes:
  grafana-data:
  grafana-conf:
  postgres-data:

networks:
  monitoring:
    driver: bridge